spring:
  datasource:
    url: '@db.jdbc.url@'
    username: '@db.user@'
    password: '@db.password@'
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: '@db.pool.max.wait@'
      max-active: '@db.pool.max.active@'
  jpa:
    show-sql: '@db.show.sql@'    
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect    
  jackson:
    serialization-inclusion: NON_EMPTY
endpoints:
  health:
    sensitive: false
    time-to-live: 100
server:
  contextPath: /angularJSProject
  port: '@server.port@'
project:
  group: core
  team: content
  env: ${spring.profiles.active}
  application: '@application.name@'
  message:
    errorFile: '@message.error.file@'     